apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: {{.Values.clusterName}}-nth
  namespace: {{ $.Release.Namespace }}
  labels:
      {{- include "labels.common" . | nindent 4 }}
spec:
  providerConfigRef:
    name: {{.Values.clusterName}}
  forProvider:
    tags:
      giantswarm.io/cluster: {{.Values.clusterName}}
      giantswarm.io/managed-by: {{ .Release.Name | quote }}
      sigs.k8s.io/cluster-api-provider-aws/cluster/{{.Values.clusterName}}: owned
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {{- $oidcDomains := include "oidcDomains" . | fromJsonArray -}}
          {{- range $index, $oidcDomain := $oidcDomains -}}
          {{- if not (eq $index 0) }}, {{ end }}{
            "Effect": "Allow",
            "Principal": {
              "Federated": "arn:{{ required "awsPartition from aws-crossplane-cluster-config-operator is not filled yet" $.Values.awsPartition }}:iam::{{ required "accountID from aws-crossplane-cluster-config-operator is not filled yet" $.Values.accountID }}:oidc-provider/{{ $oidcDomain }}"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
              "StringLike": {
                "{{$oidcDomain}}:sub": "system:serviceaccount:kube-system:aws-node-termination-handler"
              }
            }
          }
          {{- end }}
        ]
      }
    inlinePolicy:
      - name: nth-policy
        policy: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Action": [
                  "autoscaling:CompleteLifecycleAction",
                  "autoscaling:DescribeAutoScalingInstances",
                  "autoscaling:DescribeLifecycleHooks",
                  "autoscaling:DescribeTags",
                  "autoscaling:RecordLifecycleActionHeartbeat",
                  "ec2:DescribeInstances",
                  "sqs:DeleteMessage",
                  "sqs:ReceiveMessage"
                ],
                "Resource": "*"
              }
            ]
          }
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: {{.Values.clusterName}}-nth-notification
  namespace: {{ $.Release.Namespace }}
  labels:
      {{- include "labels.common" . | nindent 4 }}
spec:
  providerConfigRef:
    name: {{.Values.clusterName}}
  forProvider:
    tags:
      giantswarm.io/cluster: {{.Values.clusterName}}
      giantswarm.io/managed-by: {{ .Release.Name | quote }}
      sigs.k8s.io/cluster-api-provider-aws/cluster/{{.Values.clusterName}}: owned
    assumeRolePolicy: |
      {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Effect": "Allow",
                  "Action": [
                      "sts:AssumeRole"
                  ],
                  "Principal": {
                      "Service": [
                          "autoscaling.amazonaws.com"
                      ]
                  }
              }
          ]
      }
    inlinePolicy:
      - name: nth-policy
        policy: |
          {
              "Version": "2012-10-17",
              "Statement": [
                  {
                      "Effect": "Allow",
                      "Resource": "*",
                      "Action": [
                          "sqs:SendMessage",
                          "sqs:GetQueueUrl",
                          "sns:Publish"
                      ]
                  }
              ]
          }
